class_name HexGrid
extends RefCounted
## Hexagonal grid with offset coordinates (odd-r, pointy-top).
##
## Map source of truth: stores cells, terrain costs, and edges.
## Knows nothing about the scene tree — data only. HexRenderer consumes this object
## to create visual nodes.
##
## Coordinates: offset (Vector2i) in the public API; cube internally for
## distances, neighbors, and LOS. Convert with offset_to_cube() if needed.
##
## Extensible terrain: terrain_cost accepts any int as a key — define
## custom constants alongside HexCell's Terrain.* to expand the system.
enum EdgeType {
	NONE,
	RIVER,
	ROAD,
	WALL,
	CUSTOM,
}

const TERRAIN_COST: Dictionary = {
	HexCell.Terrain.ROAD: 1.0,
	HexCell.Terrain.PLAINS: 1.5,
	HexCell.Terrain.FOREST: 2.0,
	HexCell.Terrain.MOUNTAIN: 3.0,
	HexCell.Terrain.WATER: -1.0,
}

const EDGE_COST: Dictionary = {
	EdgeType.RIVER: 2.0,
	EdgeType.WALL: -1.0,
	EdgeType.ROAD: -0.5,
}

## Hex size in pixels (circumscribed radius, pointy-top odd-r).
const HEX_SIZE: float = 32.0
## Precalculated sqrt(3) for the offset↔pixel conversion formula (pointy-top hexes).
const HEX_SQRT3: float = 1.7320508075688772

var width: int = 0
var height: int = 0
var cells: Dictionary = {}  # Vector2i → HexCell
var edges: Dictionary = {}  # String (edge_key) → Dictionary { type: int, cost: float, ... }
var terrain_cost: Dictionary = {}
var edge_cost: Dictionary = {}
var hex_size: float = 32.0
# Minimum cost among the terrains PRESENT in cells. Lazy: calculated
# on the first request and invalidated in set_terrain/generate_cells. Computing over
# terrain_cost (the full dict) would give a lower minimum than the real one when
# the grid only uses a subset of terrains, which keeps the heuristic
# admissible but loose — exactly what find_path_astar wants to avoid.
var _min_passable_terrain_cost_cache: float = -1.0


## Creates the grid with the indicated dimensions and cost tables.
## [param cost_table]: int → float with the cost of each terrain. -1.0 = impassable.
##   If empty, uses default TERRAIN_COST.
## [param size]: hex radius in pixels. 0.0 → uses HEX_SIZE (32 px).
## [param edge_cost_table]: int → float with the additional cost of each EdgeType.
##   If empty, uses default EDGE_COST.
func _init(map_width: int = 15, map_height: int = 15, cost_table: Dictionary = {}, size: float = 0.0, edge_cost_table: Dictionary = {}) -> void:
	if map_width <= 0 or map_height <= 0:
		push_error("HexGrid: dimensiones inválidas (%d x %d), se usará 15x15" % [map_width, map_height])
		map_width = 15
		map_height = 15
	width = map_width
	height = map_height
	terrain_cost = cost_table if cost_table else TERRAIN_COST
	edge_cost = edge_cost_table if edge_cost_table else EDGE_COST
	hex_size = size if size > 0.0 else HEX_SIZE


## Generates the grid cells with [param default_terrain] in all positions.
## Clears any previous cells. Call once after _init().
func generate_cells(default_terrain: int = HexCell.Terrain.PLAINS) -> void:
	cells.clear()
	for y in height:
		for x in width:
			var coord := Vector2i(x, y)
			cells[coord] = HexCell.new(coord, default_terrain)
	_min_passable_terrain_cost_cache = -1.0


## Returns the HexCell at [param coord], or null if the coordinate does not exist.
func get_cell(coord: Vector2i) -> HexCell:
	return cells.get(coord, null)


## Returns the complete cell dictionary (Vector2i → HexCell). Read-only.
func get_all_cells() -> Dictionary:
	return cells


## Sets the terrain of the cell at [param coord]. No effect if the coordinate does not exist.
func set_terrain(coord: Vector2i, terrain: int) -> void:
	var cell := get_cell(coord)
	if cell:
		cell.terrain = terrain
		_min_passable_terrain_cost_cache = -1.0


## Returns true if [param coord] exists in the grid (was generated by generate_cells).
func is_valid(coord: Vector2i) -> bool:
	return cells.has(coord)


## Returns true if the cell exists and its terrain cost > 0 (not impassable).
func is_passable(coord: Vector2i) -> bool:
	return _get_terrain_cost(coord) > 0


## Returns the movement cost to enter [param coord].
## Returns -1.0 if the cell does not exist or the terrain is impassable.
func get_movement_cost(coord: Vector2i) -> float:
	return _get_terrain_cost(coord)


## Minimum cost among the terrains actually PRESENT in cells.
## Lazy: calculated on the first request and invalidated when the terrain changes.
## Returns 1.0 if the grid is empty or has no passable terrains.
## PathFinder.find_path_astar uses it as a heuristic factor to maintain
## admissibility without sacrificing tightness on maps with a single terrain.
func min_passable_terrain_cost() -> float:
	if _min_passable_terrain_cost_cache < 0.0:
		var min_cost := INF
		for cell: HexCell in cells.values():
			var c: float = terrain_cost.get(cell.terrain, -1.0)
			if c > 0.0 and c < min_cost:
				min_cost = c
		_min_passable_terrain_cost_cache = 1.0 if min_cost == INF else min_cost
	return _min_passable_terrain_cost_cache


## Terrain cost for [param coord]. -1.0 if the cell does not exist or terrain is unmapped.
func _get_terrain_cost(coord: Vector2i) -> float:
	var cell := get_cell(coord)
	if not cell:
		return -1.0
	return terrain_cost.get(cell.terrain, -1.0)


## Returns the additional cost of the edge between [param from] and [param to].
## 0.0 if there is no edge defined between those cells.
func get_edge_cost(from: Vector2i, to: Vector2i) -> float:
	var edge := get_edge(from, to)
	return edge.get("cost", 0.0) if not edge.is_empty() else 0.0


# --- Edges ---

## Generates the canonical key for an edge between [param a] and [param b].
## The key is symmetric: edge_key(a, b) == edge_key(b, a).
static func edge_key(a: Vector2i, b: Vector2i) -> String:
	if a.x < b.x or (a.x == b.x and a.y < b.y):
		return "%d,%d|%d,%d" % [a.x, a.y, b.x, b.y]
	return "%d,%d|%d,%d" % [b.x, b.y, a.x, a.y]


## Defines an edge between [param a] and [param b] of type [param edge_type].
## [param properties] can include "cost" to overwrite the default cost of the EdgeType.
## If an edge already exists between those cells, it replaces it.
func set_edge(a: Vector2i, b: Vector2i, edge_type: int, properties: Dictionary = {}) -> void:
	var key := edge_key(a, b)
	properties["type"] = edge_type
	if not properties.has("cost"):
		properties["cost"] = _default_edge_cost(edge_type)
	edges[key] = properties


## Returns the Dictionary of the edge between [param a] and [param b], or {} if it does not exist.
## The Dictionary includes at least "type" (int) and "cost" (float).
func get_edge(a: Vector2i, b: Vector2i) -> Dictionary:
	return edges.get(edge_key(a, b), {})


## Returns true if there is an edge defined between [param a] and [param b].
func has_edge(a: Vector2i, b: Vector2i) -> bool:
	return edges.has(edge_key(a, b))


## Removes the edge between [param a] and [param b] if it exists.
func remove_edge(a: Vector2i, b: Vector2i) -> void:
	edges.erase(edge_key(a, b))


## Returns all edges that have [param coord] as an endpoint.
## Each element is a Dictionary with "type", "cost", and extra properties.
func get_edges_for(coord: Vector2i) -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	for neighbor in get_neighbors(coord):
		var edge := get_edge(coord, neighbor)
		if not edge.is_empty():
			result.append(edge)
	return result


func _default_edge_cost(edge_type: int) -> float:
	return edge_cost.get(edge_type, 0.0)


## Serializes the entire grid (dimensions, costs, cells, edges) to a JSON Dictionary.
## Reconstruct with HexGrid.deserialize(data).
func serialize() -> Dictionary:
	var cells_data: Array = []
	for coord in cells:
		cells_data.append(cells[coord].serialize())
	var edges_data: Dictionary = {}
	for key in edges:
		edges_data[key] = edges[key].duplicate()
	return {
		"width": width,
		"height": height,
		"terrain_cost": terrain_cost.duplicate(),
		"edge_cost": edge_cost.duplicate(),
		"hex_size": hex_size,
		"cells": cells_data,
		"edges": edges_data,
	}


## NOTE: JSON serializes int keys as strings. They are converted back to int here.
static func deserialize(data: Dictionary) -> HexGrid:
	var parsed_terrain_cost: Dictionary = {}
	for key in data.get("terrain_cost", {}):
		parsed_terrain_cost[int(key)] = data["terrain_cost"][key]
	var parsed_edge_cost: Dictionary = {}
	for key in data.get("edge_cost", {}):
		parsed_edge_cost[int(key)] = data["edge_cost"][key]
	var grid := HexGrid.new(data.get("width", 15), data.get("height", 15), parsed_terrain_cost, data.get("hex_size", HEX_SIZE), parsed_edge_cost)
	grid.cells.clear()
	var cells_data: Array = data.get("cells", [])
	for cell_data in cells_data:
		var cell := HexCell.deserialize(cell_data)
		grid.cells[cell.coord] = cell
	var edges_data: Dictionary = data.get("edges", {})
	for key in edges_data:
		var entry = edges_data[key]
		if not entry is Dictionary or not entry.has("type") or not entry.has("cost"):
			push_warning("HexGrid.deserialize: edge inválido '%s' descartado (falta type/cost)" % key)
			continue
		grid.edges[key] = entry
	return grid


# --- Coordinates ---

## Odd-r offset to pixel (pointy-top hexes).
static func offset_to_pixel(coord: Vector2i, size: float = HEX_SIZE) -> Vector2:
	var x := size * HEX_SQRT3 * (coord.x + 0.5 * (coord.y & 1))
	var y := size * 1.5 * coord.y
	return Vector2(x, y)


## Pixel to nearest odd-r offset.
static func pixel_to_offset(pixel: Vector2, size: float = HEX_SIZE) -> Vector2i:
	var q: float = (HEX_SQRT3 / 3.0 * pixel.x - 1.0 / 3.0 * pixel.y) / size
	var r: float = (2.0 / 3.0 * pixel.y) / size
	return _cube_to_offset(cube_round(q, r))


## Offset to cube coordinates (for distance and direction).
static func offset_to_cube(coord: Vector2i) -> Vector3i:
	var x := coord.x - ((coord.y - (coord.y & 1)) / 2)
	var z := coord.y
	var y := -x - z
	return Vector3i(x, y, z)


## Hex distance between two offset coordinates.
static func distance(a: Vector2i, b: Vector2i) -> int:
	var ca := offset_to_cube(a)
	var cb := offset_to_cube(b)
	return maxi(absi(ca.x - cb.x), maxi(absi(ca.y - cb.y), absi(ca.z - cb.z)))


## Returns the 6 vertices of a pointy-top hexagon centered at (0,0).
## scale_factor < 1.0 shrinks the polygon (useful for visual separation).
static func hex_polygon_points(size: float, scale_factor: float = 0.95) -> PackedVector2Array:
	var pts := PackedVector2Array()
	for i in 6:
		var angle := PI / 3.0 * i - PI / 6.0
		pts.append(Vector2(cos(angle), sin(angle)) * size * scale_factor)
	return pts


## Translates the points of a hex polygon to a specific pixel position.
## Extracted helper to avoid the duplicated pattern of `for p in pts: translated.append(p + pixel)`
## in HexRenderer (batch), HexMiniMap, HexMapNode, and FogTextureRenderer.
static func translated_hex_polygon(points: PackedVector2Array, pixel: Vector2) -> PackedVector2Array:
	var result := PackedVector2Array()
	result.resize(points.size())
	for i in points.size():
		result[i] = points[i] + pixel
	return result


## Neighbors of a hex (6 directions, odd-r offset).
static func get_neighbors(coord: Vector2i) -> Array[Vector2i]:
	var parity := coord.y & 1
	var dirs: Array[Vector2i]
	if parity == 0:
		dirs = [
			Vector2i(coord.x - 1, coord.y - 1),
			Vector2i(coord.x, coord.y - 1),
			Vector2i(coord.x - 1, coord.y),
			Vector2i(coord.x + 1, coord.y),
			Vector2i(coord.x - 1, coord.y + 1),
			Vector2i(coord.x, coord.y + 1),
		]
	else:
		dirs = [
			Vector2i(coord.x, coord.y - 1),
			Vector2i(coord.x + 1, coord.y - 1),
			Vector2i(coord.x - 1, coord.y),
			Vector2i(coord.x + 1, coord.y),
			Vector2i(coord.x, coord.y + 1),
			Vector2i(coord.x + 1, coord.y + 1),
		]
	return dirs


## Reachable hexes with a given amount of movement points (Dijkstra).
## Shortcut to PathFinder.find_reachable(). Returns Dictionary[Vector2i, float]
## with the reachable hexes from [param origin] using [param movement_points].
func get_reachable_hexes(origin: Vector2i, movement_points: float) -> Dictionary:
	return PathFinder.find_reachable(origin, movement_points, self)


## Line of hexes between two coordinates (cube interpolation). Internal use for line-of-sight.
static func _hex_line(a: Vector2i, b: Vector2i) -> Array[Vector2i]:
	var n := distance(a, b)
	var result: Array[Vector2i] = []
	if n == 0:
		result.append(a)
		return result
	var ca := _cube_to_float(offset_to_cube(a))
	var cb := _cube_to_float(offset_to_cube(b))
	for i in range(n + 1):
		var t := float(i) / float(n)
		var lerped := Vector3(
			ca.x + (cb.x - ca.x) * t,
			ca.y + (cb.y - ca.y) * t,
			ca.z + (cb.z - ca.z) * t,
		)
		result.append(_cube_to_offset(cube_round(lerped.x, lerped.z)))
	return result


# --- Internals ---

static func cube_round(q: float, r: float) -> Vector3i:
	var s: float = -q - r
	var rq: float = roundf(q)
	var rr: float = roundf(r)
	var rs: float = roundf(s)
	var q_diff: float = absf(rq - q)
	var r_diff: float = absf(rr - r)
	var s_diff: float = absf(rs - s)
	if q_diff > r_diff and q_diff > s_diff:
		rq = -rr - rs
	elif r_diff > s_diff:
		rr = -rq - rs
	return Vector3i(int(rq), int(-rq - rr), int(rr))


static func _cube_to_float(c: Vector3i) -> Vector3:
	return Vector3(float(c.x), float(c.y), float(c.z))


## Ring of hexes at distance N from the origin.
func get_ring(center: Vector2i, radius: int) -> Array[Vector2i]:
	if radius == 0:
		return [center]
	var result: Array[Vector2i] = []
	var cube := offset_to_cube(center)
	var directions := [
		Vector3i(1, -1, 0), Vector3i(1, 0, -1), Vector3i(0, 1, -1),
		Vector3i(-1, 1, 0), Vector3i(-1, 0, 1), Vector3i(0, -1, 1),
	]
	# Start at center + direction[4] * radius
	var hex := Vector3i(
		cube.x + directions[4].x * radius,
		cube.y + directions[4].y * radius,
		cube.z + directions[4].z * radius,
	)
	for i in 6:
		for j in radius:
			var offset := _cube_to_offset(Vector3i(hex.x, hex.y, hex.z))
			if is_valid(offset):
				result.append(offset)
			hex = Vector3i(
				hex.x + directions[i].x,
				hex.y + directions[i].y,
				hex.z + directions[i].z,
			)
	return result


static func _cube_to_offset(cube: Vector3i) -> Vector2i:
	var col := cube.x + ((cube.z - (cube.z & 1)) / 2)
	var row := cube.z
	return Vector2i(col, row)


## Empty blocking_terrains → no terrain blocks (always returns true except for invalid cells).
## [param elevation_fn]: (coord: Vector2i) → float. If provided, blocks LOS when
## an intermediate hex has an elevation higher than the interpolated line of sight between from and to.
## Empty Callable = no elevation check (backward compat).
func get_line_of_sight(from: Vector2i, to: Vector2i, blocking_terrains: Array[int] = [], elevation_fn: Callable = Callable()) -> bool:
	if from == to:
		return true
	var line := _hex_line(from, to)
	var has_elevation := elevation_fn.is_valid()
	var from_elev: float = 0.0
	var to_elev: float = 0.0
	if has_elevation:
		from_elev = float(elevation_fn.call(from))
		to_elev = float(elevation_fn.call(to))
	var count := line.size()
	for i in range(count):
		var coord: Vector2i = line[i]
		if coord == from or coord == to:
			continue
		var cell := get_cell(coord)
		if cell and cell.terrain in blocking_terrains:
			return false
		if has_elevation:
			var cell_elev: float = float(elevation_fn.call(coord))
			var t: float = float(i) / float(count - 1)
			var line_height := from_elev + (to_elev - from_elev) * t
			if cell_elev > line_height:
				return false
	return true


## Returns hexes within [param radius] from [param origin] with clear line of sight.
## [param blocking_terrains]: terrains that interrupt LOS (e.g., MOUNTAIN, FOREST).
## [param elevation_fn]: see get_line_of_sight(). The [param origin] itself is always included.
func get_visible_cells(origin: Vector2i, radius: int, blocking_terrains: Array[int] = [], elevation_fn: Callable = Callable()) -> Array[Vector2i]:
	var result: Array[Vector2i] = [origin]
	result.append_array(_get_ring_filtered(origin, radius,
		func(coord: Vector2i) -> bool:
			return get_line_of_sight(origin, coord, blocking_terrains, elevation_fn)))
	return result


## Returns hexes within [param radius] that do NOT have LOS from [param origin].
## Complement of get_visible_cells(). Useful for highlighting shadowed areas.
func get_blocked_cells(origin: Vector2i, radius: int, blocking_terrains: Array[int] = [], elevation_fn: Callable = Callable()) -> Array[Vector2i]:
	var visible := {}
	for c in get_visible_cells(origin, radius, blocking_terrains, elevation_fn):
		visible[c] = true
	return _get_ring_filtered(origin, radius,
		func(coord: Vector2i) -> bool: return not visible.has(coord))


## Iterates rings 1..radius from [param origin] and returns coords that pass [param include].
func _get_ring_filtered(origin: Vector2i, radius: int, include: Callable) -> Array[Vector2i]:
	var result: Array[Vector2i] = []
	for r in range(1, radius + 1):
		for coord in get_ring(origin, r):
			if include.call(coord):
				result.append(coord)
	return result


## Returns all hexes adjacent to the units in [param unit_coords]
## that are not occupied by any unit. Useful for tactical zone of control.
func get_zone_of_control(unit_coords: Array[Vector2i]) -> Array[Vector2i]:
	var zoc: Dictionary = {}
	var unit_set: Dictionary = {}
	for coord in unit_coords:
		unit_set[coord] = true
	for coord in unit_coords:
		for neighbor in get_neighbors(coord):
			if not zoc.has(neighbor) and not unit_set.has(neighbor):
				if is_valid(neighbor):
					zoc[neighbor] = true
	var result: Array[Vector2i] = []
	for coord in zoc:
		result.append(coord)
	return result
